### ISSUE TITLE
AzureRM 2.0 provider compatibility 

### ISSUE THREAD

**Issue by ghost** [claranet/terraform-azurerm-vnet-peering#1]
Hello together,

this module is marked with  AzureRM compatibility  for version >= 1.32. I want to report that this module is not longer compatible with AzureRM v2.0.0.

AzureRM v2.0.0 expects at least a empty `features {}` block on each provider resource.

```
provider "azurerm" {
  features {}
}
```

This block is missing in the two provider resources at the `main.tf` of this module.

**Resources**:
[AzureRM changelog 2.0.0 (February 24, 2020)](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md#200-february-24-2020)

**Comment by rossifumax** [comment]
Hello @adresan,

Thanks for reporting this.
We'll pin the version to `< 2.0` to fix this error.

I'll keep you informed of the next release fixing this.

**Comment by Shr3ps** [comment]
https://github.com/claranet/terraform-azurerm-vnet-peering/blob/master/CHANGELOG.md#v211---2020-03-09

thanks :)
