### ISSUE TITLE
Support for different clients at provider initialization for multi tenanted environments

### ISSUE THREAD

**Issue by ghost** [claranet/terraform-azurerm-vnet-peering#2]
Hello together,

while this module can handle the vnet-peering in two subscriptions/tenants, it would be nice if the module also allow to pass a different client_id and client_secret  for each provider resource in the main.tf. 

At the moment, the authentication for each provider resource is handled by the standard environment variables, but environment variables does not support provider aliases. Because of this, its not possible to use this module with different client_ids for each provider resource wich it makes not usable for some multi tenanted environments organization structures.

As a user, i would like to expect sth. like this:

```
data "azurerm_client_config" "current_config" {
}

provider "azurerm" {
  [...]
  client_id = var.client_id_src
  client_secret = var.client_secret_src
  
  alias                      = "src"
  [...]
}

provider "azurerm" {
  [...]
  client_id = var.client_id_dest
  client_secret = var.client_secret_dest
  
  alias                      = "dest"
  [...]
}
```

**Comment by Shr3ps** [comment]
Hi, thanks for this issue and improvement suggestion, do you think you can Pull-Request this? would be a great contribution improvement!

**Comment by ghost** [comment]
Thanks for your fast reply. Yes i can do that. I will add this PR during this week and link this request to it.
